version: "2.1"

services:

  cli:
    image: ${COMPOSE_PROJECT_NAME_SAFE}/cli
    build: cli
    command: ["bash", "-lc", "nodemon --legacy-watch /var/www/index.js"]
    volumes:
      - project_root:/var/www:rw

  mongo:
    hostname: mongo
    image: mongo
    restart: always

  mongoui:
    hostname: mongoui
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
